### ISSUE TITLE
Bug related to Mysql.Data library 

### ISSUE THREAD

**Issue by yousefshura** [fabiogouw/NHiLo#11]
I found a bug in GetKeyGenerator function given by Mysql.Data namespace,
```
The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding() 
```
the bug is related to the charset in MYSQL database, they have fixed it in later releases so I have updated the package to fix the issue in the library.
The following pull request would fix this issue, https://github.com/fabiogouw/NHiLo/pull/10
Thanks

**Comment by fabiogouw** [comment]
Hello, @yousefshura! I've missed this PR, sorry for the delay. I'm going to merge it and release this patch. Thanks for your contribution.

**Comment by fabiogouw** [comment]
Patch released: https://www.nuget.org/packages/NHiLo/2.1.1
Thanks!
