### ISSUE TITLE
Package MySql.Data license is incompatible with project license.

### ISSUE THREAD

**Issue by wtjones** [fabiogouw/NHiLo#18]
Dependency [MySql.Data](https://www.nuget.org/packages/MySql.Data/) is GPL 2.0. As I understand it, software that links to it must have the same license.

Options that I am aware of:
1) Split out providers to separate projects. We would pull down oracle/mysql etc as needed. [Dbup](https://www.nuget.org/packages/dbup-mysql) does this, however the separate project seems to have the same license issue.

2) Switch to [MySqlConnector](https://www.nuget.org/packages/MySqlConnector).

I noticed this issue when scanning dependencies after pulling down NHilo. Wouldn't projects using NHilo would be subject to GPL 2?

**Comment by fabiogouw** [comment]
Thanks for sharing, @wtjones, I'll take a look which option fits better here

**Comment by fabiogouw** [comment]
At first, I thought about just changing the NHiLo's license, but after looking at some comparisons between MySqlConnector and MySql.Data (performance, community usage, etc.), changing the dependency seems to bring more benefits.
